# Generated by Django 6.1.1 on 2026-09-04 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_lat', models.FloatField()),
                ('driver_lng', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('completed', 'Completed')], default='active', max_length=10)),
                ('total_seats', models.IntegerField(default=3)),
                ('seats_available', models.IntegerField(default=3)),
                ('total_trip_fare_estimate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.campuslocation')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], max_length=10)),
                ('phone_or_matric_number', models.CharField(max_length=30)),
                ('keke_association_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('boarded', 'Boarded'), ('completed', 'Completed'), ('declined', 'Declined'), ('no_show', 'No Show')], default='pending', max_length=10)),
                ('compatibility_score', models.FloatField(default=0)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('per_rider_fare_share', models.FloatField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
                ('rider_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.campuslocation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.activetrip')),
            ],
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_riders', models.IntegerField()),
                ('fuel_cost_estimate', models.FloatField(blank=True, null=True)),
                ('fuel_cost_per_passenger', models.FloatField(blank=True, null=True)),
                ('total_trip_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rides.activetrip')),
            ],
        ),
    ]
