"""
Django settings for campusride project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&8!_x+6y4!w%$+6f%g6&v0=o5^!o4w-*p0v)0b2@1z3k2m5n8q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow ngrok and local

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rides',  # our app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campusride.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campusride.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite has no row-level locking, so transaction.atomic() blocks
        # (e.g. optimizer.optimize_trip) serialize on SQLite's own
        # database-level write lock instead. Two things are needed for that
        # to behave like a queue instead of crashing with "database table
        # is locked" under concurrent requests:
        #   - timeout: how long (seconds) a blocked connection waits for
        #     the lock before giving up. Django's own default is 5s; we
        #     raise it since optimize_trip can be called by several
        #     concurrent seat requests in a burst.
        #   - init_command PRAGMA busy_timeout mirrors the same value at
        #     the SQLite driver level (belt-and-braces; some SQLite/Python
        #     builds only honor one of the two settings).
        # This does not make SQLite suitable for high-concurrency production
        # traffic -- it only prevents the specific "table is locked" crash
        # seen under light concurrent load in tests. For real production
        # concurrency, move to Postgres, where select_for_update() in
        # optimizer.optimize_trip becomes a real per-row lock.
        'OPTIONS': {
            'timeout': 20,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom auth URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'rider_map'


# Allow ngrok (all current free/paid domains) and local development.
# Wildcard subdomains are supported in Django 4.0+.
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
    "https://*.ngrok.io",
    "https://*.ngrok.app",
    "https://*.trycloudflare.com",
    "http://localhost",
    "http://127.0.0.1",
    "http://0.0.0.0",
]

# ngrok terminates TLS; tell Django the original request was HTTPS so
# CSRF origin checks and secure cookies behave correctly.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Cookies must work over the ngrok HTTPS URL. Lax is enough for same-site
# form POSTs from the ngrok host back to itself.
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = False   # False so both http tunnel and https work in Colab
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False  # allow JS to read token if needed
CSRF_USE_SESSIONS = False
